---
version: '3'
services:
  app:
    build: .
    ports:
      - 8888:8888

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortener
      - POSTGRES_PASSWORD=password