---
version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortener
      - POSTGRES_PASSWORD=password
  app:
    build: .
    ports:
      - 8888:8888
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python /app/url_shortener.py'
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - app

