---
version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortener
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    restart: always
    build: .
    ports:
      - 8888:8888
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn -w 1 -b 0.0.0.0:8888 --chdir /app wsgi:app'
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db-data:

